server:
  port: 9001

spring:
  application:
    name: ADDRESS-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://aeb10002b6a5b43879d787cee1fa80c1-180964318.us-east-2.elb.amazonaws.com
  instance:
    hostname: address-service
