apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress-role-binding
subjects:
- kind: ServiceAccount
  name: nginx-ingress-serviceaccount
  namespace: default  
roleRef:
  kind: ClusterRole
  name: nginx-ingress-role
  apiGroup: rbac.authorization.k8s.io
