server:
  port: 9006

spring:
  application:
    name: TEST-LAB-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    hostname: test-lab-service
