apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
  - targetPort: 3306
    port: 3306
    nodePort: 30001
  selector:
    type: mysql
    