server:
  port: 9003

spring:
  application:
    name: CARD-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: 
  instance:
    hostname: card-service
